### ISSUE TITLE
SERVICE_LOGO_URL Variable no existe mas

### ISSUE THREAD

**Issue by JoaquinBarco** [yaninaerivera/Lisboa1-LastFM-Data#1]
En la clase LastFMToArtistBiographyResolver.kt hay el metodo _getLogoUrl()_ que retorna _SERVICE_LOGO_URL_, pero este ya no existe mas, deberia cambiarse a LASTFM_LOGO_URL.

**Comment by yaninaerivera** [comment]
Resuelto
